---
- name: restart gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when | bool

- name: check ssh #Check whether ssh keys are available by anonymous access
  command: grep -Fq user_for_ssh_keys_rendering /opt/gitlab/embedded/service/gitlab-rails/app/controllers/users_controller.rb
  register: ssh_result
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: show warning
  debug: msg="!!! SSH KEYS ARE NOT AVAILABLE !!! See https://confluence.agrohistory.com/pages/viewpage.action?pageId=641012587 for more details"
  when: not ssh_result.rc == 0